### create user 

POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "dev001@email.com",
    "password": "1234"
}

### Sign in 
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "tgo77@email.com",
    "password":"1234"
}


### WHO AM I 
GET http://localhost:3000/auth/whoami

### SING OUT
POST http://localhost:3000/auth/signout



### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all  users with a given Email
GET http://localhost:3000/auth?email=abc@email.com 

### Update a user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email":"abc@email.com"
}

### Delete a user given ID
DELETE http://localhost:3000/auth/2





