### create user 

POST  http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "admin@incon.kr",
    "password": "1230"
}

### Sign in 
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "admin@incon.kr",
    "password":"1230"
}


### LOGIN 
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "admin@incon.kr",
    "password":"1230"
}


### GET STATUS
GET http://localhost:3000/auth/status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBpbmNvbi5rciIsImFkbWluIjpmYWxzZSwiaWF0IjoxNzUyMDM5ODM0LCJleHAiOjE3NTIwNDM0MzR9.QpI8G9Dij9JvY1u3AtpnJp3TIETm4PcF4rKeFSBzZi0



### WHO AM I 
GET http://localhost:3000/auth/whoami

### SING OUT
POST http://localhost:3000/auth/signout



### findUser
GET http://localhost:3000/auth/1

### Find all  users with a given Email
GET http://localhost:3000/auth?email=abc@email.com 

### Update a user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email":"abc@email.com"
}

### Delete a user given ID
DELETE http://localhost:3000/auth/2





